# Case Study: Seismic Activity in Greece {#sec-casegreece}

{{< include _setupcode.qmd >}}

At the intersection of the African plate, the Eurasia plate, and the smaller Aegean plate, Greece is one of the most earthquake-prone regions in the world.  Between July 2016 and July 2017, Greece experienced 179 earthquakes; by contrast, the state of Texas experienced 28 over the same span of time.  In a region with such seismic activity, careful consideration must be given to municipal construction.  Understanding how the motion experienced in a location is related to the soil properties in the area or the magnitude and distance of an earthquake is important.

An article in the _Journal of Earthquake Engineering_ [@Koutrakis2002] examined seismic events in Greece occurring between 1978 and 1997.  Of interest for construction is characterizing the "strong ground motion," when the earth shakes with enough force to cause damage to infrastructure, with respect to the properties of a location.  The study recorded several measurements from 121 stations (representing 93 distinct seismic events)[^caveat].  The primary variable of interest is the _bracketed duration_, "the time interval [in seconds] between the first and last excursion of the peak ground acceleration beyond a certain predefined level."  For our purposes, we only consider the data corresponding to a threshold of 2% of the acceleration due to gravity.  A longer bracketed duration would correspond to more time an area is exposed to violent shaking (and therefore more time in which damage may occur).  In addition to the bracketed duration, the following measurements were available for each observation:

  - Moment Magnitude: a measure of the size of the earthquake; larger values indicate more severe earthquakes.
  - Epicentral Distance: distance (kilometers) from the epicenter of the earthquake to the location at which the measurement was taken.
  - Soil Condition: indicator of the type of soil present at the measurement site. Soil was categorized as one of three types - alluvium (soft, fine particles of clay, silt, sand, and gravel), intermediate soil conditions, or tertiary or older rock (those older than 2.58 million years). 

The first 5 observations in the dataset are shown in @tbl-casegreece-table.  In this unit, we are particularly interested in characterizing the relationship between the bracketed duration at a location and the magnitude of the corresponding earthquake.

```{r}
#| label: tbl-casegreece-table
#| tbl-cap: Data for the first 5 observations from a study characterizing seismic activity in Greece.

greece.df |>
  rename(`Bracketed Duration (s)` = BD02,
         `Distance from Epicenter (km)` = Epicentral_Distance,
         `Soil Conditions` = Soil_Condition) |>
  select(-Station_Id, -starts_with("BD")) |>
  slice(1:5) |>
  mykable()
```

[^caveat]: The original article presented repeated measurements at each location.  We present here only the first measurement from each location to simplify any analyses.  Repeated measurements are discussed briefly later in the text; for a more thorough treatment of the subject, we recommend a course in Designed Experiments or Biostatistics.  The dataset presented here corresponds to that presented in Navidi's "Statistics for Engineers and Scientists" (Chapter 8, Supplementary Exercise 22).
