# Case Study: Organic Foods and Superior Morals {#sec-caseorganic}

{{< include _setupcode.qmd >}}

"You are what you eat" is a common phrase, dating back to at least the 1820's[^phrase], used to suggest that if you want to be fit, you must eat healthy foods.  However, does the phrase extend to our personality as well as our physique?  Recent research has suggested that specific tastes (sweet vs. disgusting, for example) can influence moral processing.  That is, certain foods may lead us to be nicer to those around us or lead us to be more judgmental.  Organic foods are often marketed using phrases like "pure" or "honest" (Jessica Alba's [Honest Company](https://www.honest.com/), for example); is there some relationship between the consumption of organic foods and moral behavior?

Dr. Eskine of the Department of Psychological Sciences at Loyola University sought to answer this question [@Eskine2013].  He conducted a study to investigate whether exposure to certain types of food had an effect on a person's moral processing.  Specifically, he randomized 62 Loyola University undergraduates to one of three food types: organic, comfort, and control.  Each participant received a packet containing pictures of four food items from the assigned category:

  - Organic Foods: apple, spinach, tomato, carrot
  - Comfort Foods: ice cream, cookie, chocolate, brownie
  - Control Foods: oatmeal, rice, mustard, beans
  
The control foods chosen are pre-packaged and are generally considered staple items; organic foods chosen are associated with a healthy diet; and, comfort foods were sweets.  After viewing the images for a set period of time, each participant received a packet containing six counter-balanced moral transgressions.  An example of such a transgression is produced below:

  > Bob was at a family gathering when he met Ellen, a second cousin of his that he had seen once or twice before.  Bob found Ellen very attractive and he asked her out on a date.  Ellen accepted and they began to have a romantic and sexual relationship.  They often go on weekend trips to romantic hotels in the mountains.
  
Participants were then asked to rate the morality of the scenario on a 7-point scale (1 = "not at all morally wrong" to 7 = "very morally wrong").  The average of the morality scores across the six scenarios was used as an overall measure of their moral expectations.  A higher value indicates high moral expectations (very strict), and a lower value indicates lower moral expectations (very lenient).

Dr. Eskine's analysis revealed the study provided strong evidence ($p = 0.001$) that participants' moral judgments differed, on average, across the various food exposure groups.  In particular, those exposed to organic foods had higher moral expectations (an average mean moral judgment of 5.58) compared to those experiencing comfort foods (average mean moral judgment of 4.89) or control foods (average mean moral judgment of 5.08).  He therefore concluded that exposure to organic food led to higher moral expectations among the participants.

Understandably, Dr. Eskine's work caught the interest of various media outlets and researchers.  Two researchers within the Department of Psychology at Dominican University in Illinois sought to replicate Dr. Eskine's work [@Moery2016].  There were several components to their research, but the first phase included a replication of Dr. Eskine's initial study with minor variants.  They enrolled `r nrow(organic.df)` college students into their study.  The participants were presented with the same food images as in Eskine's study with the exception that celery was used instead of an apple for organic food.  The same moral dilemmas were given to participants.  As in the original study, the average score from the six moral dilemmas was the primary response for this study.  A subset of the collected data, showing three participants from each treatment group (type of food shown), is presented in @tbl-caseorganic-table.  The full dataset has been made available by the researchers[^fulldata].

```{r}
#| label: tbl-caseorganic-table
#| tbl-cap: Subset of data from study characterizing moral behavior following exposure to various food categories.

organic.df |>
  select(Participant, Food_Condition, moral_avg) |>
  group_by(Food_Condition) |>
  arrange(Participant) |>
  rename(`Food Condition` = Food_Condition,
         `Response (Avg of Moral Questions)` = moral_avg) |>
  slice(1:3) |>
  mykable(digits = 3)
```

[^phrase]: [https://www.phrases.org.uk/meanings/you-are-what-you-eat.html](https://www.phrases.org.uk/meanings/you-are-what-you-eat.html)

[^fulldata]: There were multiple phases to their research.  The direct replication of Dr. Eskine's work was Study 1, which is the dataset being considered in this text; it is available at [https://osf.io/atkn7/wiki/home/](https://osf.io/atkn7/wiki/home/).
